Repository BitcreditProtocol/wildcat-dashboard-ui, pull requests merged in 2025-06, with the labels that each got.

#38 Update UI Dashboard 2
  src/components/AppSidebar.tsx
  src/generated/client/sdk.gen.ts
  src/generated/client/types.gen.ts
  src/main.tsx
  src/pages/quotes/QuotePage.tsx
  src/pages/quotes/StatusQuotePage.tsx
Labels: Review effort 3/5

#49 change treasury-service endpoint
  src/constants/endpoints.ts
  src/generated/client/sdk.gen.ts
  src/generated/client/types.gen.ts
  src/lib/api.ts
  src/pages/balances/CashFlowPage.tsx
  src/pages/balances/EarningsPage.tsx
Labels: Review effort 1/5

#60 feat(ci): implement deployment workflow for tagged versions
  .github/workflows/deploy-wildcat-docker.yml
Labels: Review effort 3/5

#62 fix(ci): allow deployment workflow to run via manual dispatch
  .github/workflows/deploy-wildcat-docker.yml
Labels: Review effort 2/5
